version: '3.8'

services:
  db:
    image: postgres:15
    container_name: jobmarket_db
    environment:
      POSTGRES_DB: jobmarket
      POSTGRES_USER: jobmarket
      POSTGRES_PASSWORD: jobmarket123
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - jobmarket_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jobmarket"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: jobmarket_web
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://jobmarket:jobmarket123@db:5432/jobmarket
      SESSION_SECRET: your-super-secret-key-change-this-in-production-environment
      FLASK_ENV: development
      PYTHONPATH: /app
    volumes:
      - .:/app:ro  # Read-only mount for security
      - uploads:/app/uploads  # Persistent storage for uploads
    depends_on:
      db:
        condition: service_healthy
    networks:
      - jobmarket_network
    restart: unless-stopped
    command: >
      sh -c "
        echo 'Waiting for database to be ready...' &&
        sleep 5 &&
        echo 'Initializing database tables...' &&
        python -c 'from models import db; from app import server; 
        with server.app_context(): 
          db.create_all(); 
          print(\"Database tables created successfully\")' &&
        echo 'Starting Gunicorn server...' &&
        gunicorn --bind 0.0.0.0:5000 --workers 2 --timeout 120 --reload main:server
      "

  # Optional: Redis for session storage and caching
  redis:
    image: redis:7-alpine
    container_name: jobmarket_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - jobmarket_network
    command: redis-server --appendonly yes
    restart: unless-stopped

  # Optional: Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: jobmarket_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - web
    networks:
      - jobmarket_network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  uploads:
    driver: local

networks:
  jobmarket_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16